version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: medical-appointments-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical-appointments
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - consultas-network

networks:
  consultas-network:
    driver: bridge

volumes:
  postgres_data: